---@class opencode.Provider
---
---Called by `require("opencode").toggle()`.
---@field toggle fun()
---
---Called when no `opencode` process is found so you can start it,
---after which `opencode.nvim` will poll for a couple seconds to see if one appears.
---@field start fun()
---
---Called when a prompt or command is sent to `opencode`.
---@field show fun()

---@alias opencode.provider.Opts
---| opencode.Provider
---| { name: "snacks", opts: { cmd: string }|snacks.terminal.Opts }
